import type { Metadata } from "next";
import "./globals.css";
import "aos/dist/aos.css";

import { AOSProvider } from "@/lib/utils/AOSProvider";

export const metadata: Metadata = {
  title: "BookOwl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSProvider />
      <body
        className=""
      >
        {children}
      </body>
    </html>
  );
}
